on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test local action
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use local action to create .npmrc
        uses: ./create
        with:
          token: "notreallyatoken"
      - name: Make sure it contains the token
        shell: bash
        run: |
          cd ~
          grep -o "notreallyatoken" .npmrc | wc -l
      - name: Use local action to remove .npmrc
        uses: ./remove
      - name: Make sure the token is removed
        shell: bash
        run: |
          cd ~
          ! grep -o "notreallyatoken" .npmrc | wc -l
